export const LIST_REQUEST = 'LIST_REQUEST'
export const LIST_REQUEST_SUCCESS = 'LIST_REQUEST_SUCCESS'
export const LIST_REQUEST_FAIL = 'LIST_REQUEST_FAIL'

export const AUTHOR_REQUEST = 'AUTHOR_REQUEST'
export const AUTHOR_REQUEST_SUCCESS = 'AUTHOR_REQUEST_SUCCESS'
export const AUTHOR_REQUEST_FAIL = 'AUTHOR_REQUEST_FAIL'

export const BOOKS_BY_AUTHOR_REQUEST = 'BOOKS_BY_AUTHOR_REQUEST'
export const BOOKS_BY_AUTHOR_REQUEST_SUCCESS = 'BOOKS_BY_AUTHOR_REQUEST_SUCCESS'
export const BOOKS_BY_AUTHOR_REQUEST_FAIL = 'BOOKS_BY_AUTHOR_REQUEST_FAIL'

export const BOOK_INFO_REQUEST = 'BOOK_INFO_REQUEST'
export const BOOK_INFO_REQUEST_SUCCESS = 'BOOK_INFO_REQUEST_SUCCESS'
export const BOOK_INFO_REQUEST_FAIL = 'BOOK_INFO_REQUEST_FAIL'
